version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: civjs-postgres
    environment:
      POSTGRES_USER: civjs
      POSTGRES_PASSWORD: civjs_secret
      POSTGRES_DB: civjs
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - civjs-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U civjs']
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: civjs-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - civjs-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  # Game Server
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: civjs-server
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://civjs:civjs_secret@postgres:5432/civjs
      REDIS_URL: redis://redis:6379
      SOCKET_CORS_ORIGIN: '*'
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - civjs-network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

networks:
  civjs-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
