[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"

# Run migrations before starting the server
startCommand = "npm run start:prod"
