/**
 * @module client/components/Canvas2D/tilesets/Amplio2TilesetProvider
 * Loads the revisioned square-isometric package generated by freeciv-web's
 * own Amplio2 extractor. Geometry, terrain composition, sprite rectangles,
 * and presentation offsets all come from one provider-owned manifest.
 *
 * @reference reference/freeciv-web/freeciv/version.txt
 * @reference reference/freeciv-web/scripts/freeciv-img-extract/img-extract.py
 * @reference reference/freeciv-web/freeciv-web/src/main/webapp/javascript/2dcanvas/tileset_config_amplio2.js
 */
import {
  getTilesetTopologyCompatibility,
  type TerrainCompositionProfile,
  type TilesetGeometry,
  type TilesetMetadata,
  type TilesetPresentationOffsets,
  type TilesetProvider,
  type TilesetRenderProfile,
} from './TilesetProvider';

interface Amplio2SpriteRectangle {
  image: string;
  x: number;
  y: number;
  width: number;
  height: number;
}

interface Amplio2Manifest {
  schemaVersion: number;
  id: string;
  name: string;
  sourceWebRevision: string;
  sourceFreecivRevision: string;
  topologyId: number;
  geometry: TilesetGeometry;
  offsets: TilesetPresentationOffsets;
  terrainComposition: TerrainCompositionProfile;
  renderProfile: TilesetRenderProfile;
  preloadImages: string[];
  sprites: Record<string, Amplio2SpriteRectangle>;
}

const FALLBACK_GEOMETRY: TilesetGeometry = {
  tileWidth: 96,
  tileHeight: 48,
  fullTileWidth: 96,
  fullTileHeight: 48,
  hexWidth: 0,
  hexHeight: 0,
};

const FALLBACK_OFFSETS: TilesetPresentationOffsets = {
  unitFlagX: 25,
  unitFlagY: -16,
  cityFlagX: 2,
  cityFlagY: -9,
  unitX: 19,
  unitY: -14,
  activityX: 55,
  activityY: -25,
  selectX: 0,
  selectY: 0,
  stackX: 0,
  stackY: -31,
  cityX: 0,
  cityY: -14,
  citybarX: 45,
  citybarY: 55,
  tileLabelX: 0,
  tileLabelY: 15,
};

export class Amplio2TilesetProvider implements TilesetProvider {
  readonly metadata: TilesetMetadata = {
    id: 'amplio2',
    name: 'Amplio2',
    format: 'freeciv-web',
    projection: 'isometric',
    topologyId: 1,
  };

  private manifest: Amplio2Manifest | null = null;
  private images = new Map<string, HTMLImageElement>();
  private sprites = new Map<string, HTMLCanvasElement>();
  private loadGeneration = 0;

  async load(): Promise<void> {
    const generation = ++this.loadGeneration;
    const response = await fetch('/tilesets/amplio2/manifest.json');
    if (!response.ok) throw new Error(`Failed to load Amplio2 manifest (${response.status})`);
    const manifest = (await response.json()) as Amplio2Manifest;
    if (
      manifest.schemaVersion !== 1 ||
      manifest.id !== this.metadata.id ||
      manifest.topologyId !== this.metadata.topologyId
    ) {
      throw new Error('Unsupported Amplio2 manifest');
    }

    const loadedImages = await Promise.all(
      manifest.preloadImages.map(async source => [source, await this.loadImage(source)] as const)
    );
    if (generation !== this.loadGeneration) throw new Error('Tileset load cancelled');

    this.images = new Map(loadedImages);
    this.sprites.clear();
    this.manifest = manifest;
  }

  private loadImage(source: string): Promise<HTMLImageElement> {
    return new Promise((resolve, reject) => {
      const image = new Image();
      image.onload = () => resolve(image);
      image.onerror = () => reject(new Error(`Failed to load Amplio2 image ${source}`));
      image.src = `/tilesets/amplio2/${source}`;
    });
  }

  private getCandidates(tag: string): string[] {
    const bare = tag.endsWith(':0') ? tag.slice(0, -2) : tag;
    const candidates = [tag, bare, `${bare}:0`];
    if (bare.startsWith('u.') && !bare.endsWith('_Idle')) candidates.push(`${bare}_Idle`);
    return [...new Set(candidates)];
  }

  getSprite(tag: string): HTMLCanvasElement | null {
    for (const candidate of this.getCandidates(tag)) {
      const cached = this.sprites.get(candidate);
      if (cached) return cached;
      const rectangle = this.manifest?.sprites[candidate];
      if (!rectangle) continue;
      const image = this.images.get(rectangle.image);
      if (!image) continue;

      const canvas = document.createElement('canvas');
      canvas.width = rectangle.width;
      canvas.height = rectangle.height;
      const context = canvas.getContext('2d');
      if (!context) continue;
      context.drawImage(
        image,
        rectangle.x,
        rectangle.y,
        rectangle.width,
        rectangle.height,
        0,
        0,
        rectangle.width,
        rectangle.height
      );
      this.sprites.set(candidate, canvas);
      return canvas;
    }
    return null;
  }

  hasSprite(tag: string): boolean {
    return this.getCandidates(tag).some(candidate => Boolean(this.manifest?.sprites[candidate]));
  }

  hasNativeSprite(tag: string): boolean {
    return this.hasSprite(tag);
  }

  hasTerrainDefinition(graphic: string): boolean {
    return Boolean(this.manifest?.terrainComposition.terrains[graphic]);
  }

  isReady(): boolean {
    return this.manifest !== null;
  }

  getTileSize(): { width: number; height: number } {
    const geometry = this.getGeometry();
    return { width: geometry.tileWidth, height: geometry.tileHeight };
  }

  getGeometry(): TilesetGeometry {
    return this.manifest?.geometry ?? FALLBACK_GEOMETRY;
  }

  getTopologyCompatibility(topologyId: number) {
    return getTilesetTopologyCompatibility(topologyId, this.metadata.topologyId);
  }

  getTerrainComposition(): TerrainCompositionProfile | null {
    return this.manifest?.terrainComposition ?? null;
  }

  getPresentationOffsets(): TilesetPresentationOffsets {
    return this.manifest?.offsets ?? FALLBACK_OFFSETS;
  }

  getRenderProfile(): TilesetRenderProfile | null {
    return this.manifest?.renderProfile ?? null;
  }

  getAvailableSprites(): string[] {
    return Object.keys(this.manifest?.sprites ?? {});
  }

  findSprites(pattern: string): string[] {
    const normalized = pattern.toLowerCase();
    return this.getAvailableSprites().filter(key => key.toLowerCase().includes(normalized));
  }

  dispose(): void {
    this.loadGeneration += 1;
    this.manifest = null;
    this.images.clear();
    this.sprites.clear();
  }
}
