name: Maintenance & Dependencies

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  # ================================
  # DEPENDENCY UPDATES
  # ================================
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: moderate

  # ================================
  # CODE QUALITY MONITORING
  # ================================
  code-quality:
    name: Code Quality Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Generate complexity report
        run: |
          npx typescript-complexity-report --output-format json > complexity-report.json || true

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: quality-reports
          path: |
            coverage/
            complexity-report.json

  # ================================
  # SECURITY MONITORING
  # ================================
  security-monitoring:
    name: Security Monitoring
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Security audit
        run: |
          echo "## Security Audit Report" > security-report.md
          echo "Generated on: $(date)" >> security-report.md
          echo "" >> security-report.md
          npm audit --json > audit-raw.json || true
          npx better-npm-audit audit --output-format text >> security-report.md || true

      - name: Check for outdated dependencies
        run: |
          echo "" >> security-report.md
          echo "## Outdated Dependencies" >> security-report.md
          npm outdated >> security-report.md || true

      - name: Upload security report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: security-report.md

  # ================================
  # DOCKER BUILD VERIFICATION
  # ================================
  docker-maintenance:
    name: Docker Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Docker build
        run: docker build -t civjs-server:test .

      - name: Verify Docker image
        run: |
          echo "✅ Docker build successful"
          docker images civjs-server:test
