/** Nation IDs retained from the base Civilization III–V rosters. */
export const CIV_3_TO_5_NATION_IDS = new Set([
  'american',
  'arab',
  'aztec',
  'babylonian',
  'chinese',
  'egyptian',
  'english',
  'french',
  'german',
  'greek',
  'indian',
  'inca',
  'iroquois',
  'japanese',
  'mali',
  'mongol',
  'ottoman',
  'persian',
  'roman',
  'russian',
  'spanish',
  'thai',
  'zulu',
]);
